//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Railway_MiniProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Detail
    {
        public int Class_ID { get; set; }
        public Nullable<int> Train_No { get; set; }
        public string Class_Name { get; set; }
        public int Total_Seats { get; set; }
        public int Available_Seats { get; set; }
        public Nullable<decimal> Fare { get; set; }
    
        public virtual Train Train { get; set; }
    }
}
